/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oauth.h"
#include "oauth_client.h"
#include "utils.h"
#include <vector>
#include <unordered_map>

std::vector<operation_props> operations;
std::unordered_map<std::string, std::string> user_to_acces_token;

void
oauth_prog_1(char *host)
{
	CLIENT *clnt;
	request_authorization_res  *result_1;
	request_authorization_props request_authorization_1_arg1;
	approve_request_token_res  *result_2;
	approve_request_token_props approve_request_token_1_arg1;
	request_access_token_res  *result_3;
	request_access_token_props request_access_token_1_arg1;
	refresh_tokens_res  *result_4;
	refresh_tokens_props refresh_tokens_1_arg1;
	validate_delegated_action_res  *result_5;
	validate_delegated_action_res validate_delegated_action_1_arg1;

	clnt = clnt_create (host, OAUTH_PROG, OAUTH_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	for (int i = 0; i < operations.size(); ++i) {
		if (operations[i].action == REQUEST) {
			// Request an authorization token
			result_1 = request_authorization_1((request_authorization_props) {
				.client_id = (char *) operations[i].user_id.c_str(),
				.auto_refresh = operations[i].automatic_refresh,
			}, clnt);

			if (result_1 == (request_authorization_res *) NULL) {
				clnt_perror (clnt, "call failed");
			} else {
				if (result_1->err == 0) {
					// Request for the final user to sign the authorization token
					// with the permissions specified in "approvals.db"
					result_2 = approve_request_token_1((approve_request_token_props) {
						.authorization_token = result_1->request_authorization_res_u.token,
					}, clnt);

					if (result_2 == (approve_request_token_res *) NULL) {
						clnt_perror (clnt, "call failed");
					} else {
						// Request for an access and an optiional refresh token
						// (if the authorization token was generated with the
						// automatic refresh option enabled)
						result_3 = request_access_token_1((request_access_token_props) {
							.client_id = (char *) operations[i].user_id.c_str(),
							.authorization_token = result_1->request_authorization_res_u.token,
						}, clnt);

						if (result_3 == (request_access_token_res *) NULL) {
							clnt_perror (clnt, "call failed");
						} else {
							if (result_3->err == 0) {
								std::cout << result_1->request_authorization_res_u.token <<
									" -> " << result_3->request_access_token_res_u.tokens.access_token;
								user_to_acces_token[operations[i].user_id] =
									result_3->request_access_token_res_u.tokens.access_token;
								
								if ((std::string)result_3->request_access_token_res_u.tokens.refresh_token != "")
									std::cout << "," << result_3->request_access_token_res_u.tokens.refresh_token << std::endl;
								else
									std::cout << std::endl;
							} else if (result_3->err == REQUEST_DENIED) {
								std::cout << MACRO_RAW(REQUEST_DENIED) << std::endl;
							}
						}
					}

				} else if (result_1->err == USER_NOT_FOUND) {
					std::cout << MACRO_RAW(USER_NOT_FOUND) << std::endl;
				}
			}
		} else {
			result_5 = validate_delegated_action_1((validate_delegated_action_props) {
				.operation = (char *) operations[i].action.c_str(),
				.resource = operations[i].resource,
				.access_token = (char *) user_to_acces_token[operations[i].user_id].c_str(),
			}, clnt);

			if (result_5 == (validate_delegated_action_res *) NULL) {
				clnt_perror (clnt, "call failed");
			} else {
				switch (*result_5) {
					case PERMISSION_DENIED:
						std::cout << MACRO_RAW(PERMISSION_DENIED) << std::endl;
						break;
					case TOKEN_EXPIRED:
						std::cout << MACRO_RAW(TOKEN_EXPIRED) << std::endl;
						break;
					case RESOURCE_NOT_FOUND:
						std::cout << MACRO_RAW(RESOURCE_NOT_FOUND) << std::endl;
						break;
					case OPERATION_NOT_PERMITTED:
						std::cout << MACRO_RAW(OPERATION_NOT_PERMITTED) << std::endl;
						break;
					case PERMISSION_GRANTED:
						std::cout << MACRO_RAW(PERMISSION_GRANTED) << std::endl;
						break;
				}
			}

			// if (operations[i].action == READ) {

			// } else if (operations[i].action == INSERT) {

			// } else if (operations[i].action == MODIFY) {

			// } else if (operations[i].action == DELETE) {

			// } else if (operations[i].action == EXECUTE) {

			// }
		}
	}

	
	
	
	// result_4 = refresh_tokens_1(refresh_tokens_1_arg1, clnt);
	// if (result_4 == (refresh_tokens_res *) NULL) {
	// 	clnt_perror (clnt, "call failed");
	// }
	

	clnt_destroy (clnt);
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s <server_host> <input_file>\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	std::vector<std::string> input_lines;
	get_lines_from_file(argv[2], false, input_lines);

	for (int i = 0; i < input_lines.size(); ++i) {
		int user_id = input_lines[i].find(',');
		int action = input_lines[i].find(',', user_id + 1);
		int resource = input_lines[i].find(',', action + 1);

		operations.push_back((operation_props) {
			.user_id = input_lines[i].substr(0, user_id),
			.action = input_lines[i].substr(user_id + 1, action - user_id - 1),
		});

		std::string resource_str = input_lines[i].substr(action + 1, resource - action - 1);

		if (operations[i].action == REQUEST) {
			operations[i].automatic_refresh = resource_str == "1";
		} else {
			// resource_str is a local variable to this string, and storing a temporary
			// pointer to the internal buffer of this string would make all the char*
			// pointers in the operations vector point to the same buffer
			operations[i].resource = strdup((char *) resource_str.c_str());
		}
	}

	oauth_prog_1 (host);
exit (0);
}
