/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "oauth.h"
#include "oauth_server.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static request_authorization_res *
_request_authorization_1 (request_authorization_props  *argp, struct svc_req *rqstp)
{
	return (request_authorization_1_svc(*argp, rqstp));
}

static approve_request_token_res *
_approve_request_token_1 (approve_request_token_props  *argp, struct svc_req *rqstp)
{
	return (approve_request_token_1_svc(*argp, rqstp));
}

static request_access_token_res *
_request_access_token_1 (request_access_token_props  *argp, struct svc_req *rqstp)
{
	return (request_access_token_1_svc(*argp, rqstp));
}

static refresh_tokens_res *
_refresh_tokens_1 (refresh_tokens_props  *argp, struct svc_req *rqstp)
{
	return (refresh_tokens_1_svc(*argp, rqstp));
}

static validate_delegated_action_res *
_validate_delegated_action_1 (validate_delegated_action_props  *argp, struct svc_req *rqstp)
{
	return (validate_delegated_action_1_svc(*argp, rqstp));
}

static void
oauth_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		request_authorization_props request_authorization_1_arg;
		approve_request_token_props approve_request_token_1_arg;
		request_access_token_props request_access_token_1_arg;
		refresh_tokens_props refresh_tokens_1_arg;
		validate_delegated_action_props validate_delegated_action_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case REQUEST_AUTHORIZATION:
		_xdr_argument = (xdrproc_t) xdr_request_authorization_props;
		_xdr_result = (xdrproc_t) xdr_request_authorization_res;
		local = (char *(*)(char *, struct svc_req *)) _request_authorization_1;
		break;

	case APPROVE_REQUEST_TOKEN:
		_xdr_argument = (xdrproc_t) xdr_approve_request_token_props;
		_xdr_result = (xdrproc_t) xdr_approve_request_token_res;
		local = (char *(*)(char *, struct svc_req *)) _approve_request_token_1;
		break;

	case REQUEST_ACCESS_TOKEN:
		_xdr_argument = (xdrproc_t) xdr_request_access_token_props;
		_xdr_result = (xdrproc_t) xdr_request_access_token_res;
		local = (char *(*)(char *, struct svc_req *)) _request_access_token_1;
		break;

	case REFRESH_TOKENS:
		_xdr_argument = (xdrproc_t) xdr_refresh_tokens_props;
		_xdr_result = (xdrproc_t) xdr_refresh_tokens_res;
		local = (char *(*)(char *, struct svc_req *)) _refresh_tokens_1;
		break;

	case VALIDATE_DELEGATED_ACTION:
		_xdr_argument = (xdrproc_t) xdr_validate_delegated_action_props;
		_xdr_result = (xdrproc_t) xdr_validate_delegated_action_res;
		local = (char *(*)(char *, struct svc_req *)) _validate_delegated_action_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (OAUTH_PROG, OAUTH_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, OAUTH_PROG, OAUTH_VERS, oauth_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (OAUTH_PROG, OAUTH_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, OAUTH_PROG, OAUTH_VERS, oauth_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (OAUTH_PROG, OAUTH_VERS, tcp).");
		exit(1);
	}

	// Extract the command line arguments
	char *clients_file = argv[1];
	char *resources_file = argv[2];
	char *permissions_file = argv[3];
	int tokens_validity = atoi(argv[4]);

	server_init_props props = (server_init_props){
		.clients_file = clients_file,
		.resources_file = resources_file,
		.permissions_file = permissions_file,
		.tokens_validity = tokens_validity
	};

	// Initialize all the databases
	server_init(&props);

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
