/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "oauth.h"

bool_t
xdr_client_id_t (XDR *xdrs, client_id_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 15))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_token_t (XDR *xdrs, token_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operation_t (XDR *xdrs, operation_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resource_t (XDR *xdrs, resource_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bearer_tokens_t (XDR *xdrs, bearer_tokens_t *objp)
{
	register int32_t *buf;

	 if (!xdr_token_t (xdrs, &objp->access_token))
		 return FALSE;
	 if (!xdr_token_t (xdrs, &objp->refresh_token))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_authorization_props (XDR *xdrs, request_authorization_props *objp)
{
	register int32_t *buf;

	 if (!xdr_client_id_t (xdrs, &objp->client_id))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->auto_refresh))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_authorization_res (XDR *xdrs, request_authorization_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_token_t (xdrs, &objp->request_authorization_res_u.token))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_approve_request_token_props (XDR *xdrs, approve_request_token_props *objp)
{
	register int32_t *buf;

	 if (!xdr_token_t (xdrs, &objp->authorization_token))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_approve_request_token_res (XDR *xdrs, approve_request_token_res *objp)
{
	register int32_t *buf;

	 if (!xdr_bool (xdrs, &objp->was_signed))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_access_token_props (XDR *xdrs, request_access_token_props *objp)
{
	register int32_t *buf;

	 if (!xdr_client_id_t (xdrs, &objp->client_id))
		 return FALSE;
	 if (!xdr_token_t (xdrs, &objp->authorization_token))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_access_token_res (XDR *xdrs, request_access_token_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_bearer_tokens_t (xdrs, &objp->request_access_token_res_u.tokens))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_refresh_tokens_props (XDR *xdrs, refresh_tokens_props *objp)
{
	register int32_t *buf;

	 if (!xdr_token_t (xdrs, &objp->refresh_token))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_refresh_tokens_res (XDR *xdrs, refresh_tokens_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_bearer_tokens_t (xdrs, &objp->refresh_tokens_res_u.tokens))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_validate_delegated_action_props (XDR *xdrs, validate_delegated_action_props *objp)
{
	register int32_t *buf;

	 if (!xdr_operation_t (xdrs, &objp->operation))
		 return FALSE;
	 if (!xdr_resource_t (xdrs, &objp->resource))
		 return FALSE;
	 if (!xdr_token_t (xdrs, &objp->access_token))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_delegated_action_res (XDR *xdrs, validate_delegated_action_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}
