/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OAUTH_H_RPCGEN
#define _OAUTH_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *client_id_t;

typedef char *token_t;

typedef char *operation_t;

typedef char *resource_t;

struct bearer_tokens_t {
	token_t access_token;
	token_t refresh_token;
};
typedef struct bearer_tokens_t bearer_tokens_t;

struct request_authorization_props {
	client_id_t client_id;
	bool_t auto_refresh;
};
typedef struct request_authorization_props request_authorization_props;

struct request_authorization_res {
	int err;
	union {
		token_t token;
	} request_authorization_res_u;
};
typedef struct request_authorization_res request_authorization_res;

struct approve_request_token_props {
	token_t authorization_token;
};
typedef struct approve_request_token_props approve_request_token_props;

struct approve_request_token_res {
	bool_t was_signed;
};
typedef struct approve_request_token_res approve_request_token_res;

struct request_access_token_props {
	client_id_t client_id;
	token_t authorization_token;
};
typedef struct request_access_token_props request_access_token_props;

struct request_access_token_res {
	int err;
	union {
		bearer_tokens_t tokens;
	} request_access_token_res_u;
};
typedef struct request_access_token_res request_access_token_res;

struct refresh_tokens_props {
	token_t refresh_token;
};
typedef struct refresh_tokens_props refresh_tokens_props;

struct refresh_tokens_res {
	int err;
	union {
		bearer_tokens_t tokens;
	} refresh_tokens_res_u;
};
typedef struct refresh_tokens_res refresh_tokens_res;

struct validate_delegated_action_props {
	operation_t operation;
	resource_t resource;
	token_t access_token;
};
typedef struct validate_delegated_action_props validate_delegated_action_props;

struct validate_delegated_action_res {
	int status;
};
typedef struct validate_delegated_action_res validate_delegated_action_res;

#define OAUTH_PROG 0x31234567
#define OAUTH_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define REQUEST_AUTHORIZATION 1
extern  request_authorization_res * request_authorization_1(request_authorization_props , CLIENT *);
extern  request_authorization_res * request_authorization_1_svc(request_authorization_props , struct svc_req *);
#define APPROVE_REQUEST_TOKEN 2
extern  approve_request_token_res * approve_request_token_1(approve_request_token_props , CLIENT *);
extern  approve_request_token_res * approve_request_token_1_svc(approve_request_token_props , struct svc_req *);
#define REQUEST_ACCESS_TOKEN 3
extern  request_access_token_res * request_access_token_1(request_access_token_props , CLIENT *);
extern  request_access_token_res * request_access_token_1_svc(request_access_token_props , struct svc_req *);
#define REFRESH_TOKENS 4
extern  refresh_tokens_res * refresh_tokens_1(refresh_tokens_props , CLIENT *);
extern  refresh_tokens_res * refresh_tokens_1_svc(refresh_tokens_props , struct svc_req *);
#define VALIDATE_DELEGATED_ACTION 5
extern  validate_delegated_action_res * validate_delegated_action_1(validate_delegated_action_props , CLIENT *);
extern  validate_delegated_action_res * validate_delegated_action_1_svc(validate_delegated_action_props , struct svc_req *);
extern int oauth_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REQUEST_AUTHORIZATION 1
extern  request_authorization_res * request_authorization_1();
extern  request_authorization_res * request_authorization_1_svc();
#define APPROVE_REQUEST_TOKEN 2
extern  approve_request_token_res * approve_request_token_1();
extern  approve_request_token_res * approve_request_token_1_svc();
#define REQUEST_ACCESS_TOKEN 3
extern  request_access_token_res * request_access_token_1();
extern  request_access_token_res * request_access_token_1_svc();
#define REFRESH_TOKENS 4
extern  refresh_tokens_res * refresh_tokens_1();
extern  refresh_tokens_res * refresh_tokens_1_svc();
#define VALIDATE_DELEGATED_ACTION 5
extern  validate_delegated_action_res * validate_delegated_action_1();
extern  validate_delegated_action_res * validate_delegated_action_1_svc();
extern int oauth_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_client_id_t (XDR *, client_id_t*);
extern  bool_t xdr_token_t (XDR *, token_t*);
extern  bool_t xdr_operation_t (XDR *, operation_t*);
extern  bool_t xdr_resource_t (XDR *, resource_t*);
extern  bool_t xdr_bearer_tokens_t (XDR *, bearer_tokens_t*);
extern  bool_t xdr_request_authorization_props (XDR *, request_authorization_props*);
extern  bool_t xdr_request_authorization_res (XDR *, request_authorization_res*);
extern  bool_t xdr_approve_request_token_props (XDR *, approve_request_token_props*);
extern  bool_t xdr_approve_request_token_res (XDR *, approve_request_token_res*);
extern  bool_t xdr_request_access_token_props (XDR *, request_access_token_props*);
extern  bool_t xdr_request_access_token_res (XDR *, request_access_token_res*);
extern  bool_t xdr_refresh_tokens_props (XDR *, refresh_tokens_props*);
extern  bool_t xdr_refresh_tokens_res (XDR *, refresh_tokens_res*);
extern  bool_t xdr_validate_delegated_action_props (XDR *, validate_delegated_action_props*);
extern  bool_t xdr_validate_delegated_action_res (XDR *, validate_delegated_action_res*);

#else /* K&R C */
extern bool_t xdr_client_id_t ();
extern bool_t xdr_token_t ();
extern bool_t xdr_operation_t ();
extern bool_t xdr_resource_t ();
extern bool_t xdr_bearer_tokens_t ();
extern bool_t xdr_request_authorization_props ();
extern bool_t xdr_request_authorization_res ();
extern bool_t xdr_approve_request_token_props ();
extern bool_t xdr_approve_request_token_res ();
extern bool_t xdr_request_access_token_props ();
extern bool_t xdr_request_access_token_res ();
extern bool_t xdr_refresh_tokens_props ();
extern bool_t xdr_refresh_tokens_res ();
extern bool_t xdr_validate_delegated_action_props ();
extern bool_t xdr_validate_delegated_action_res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OAUTH_H_RPCGEN */
