/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oauth.h"

char **
request_authorization_1_svc(REQUEST_AUTHORIZATION_PROPS arg1,  struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	result = "asd";

	return &result;
}
