/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "oauth.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

request_authorization_res *
request_authorization_1(request_authorization_props arg1,  CLIENT *clnt)
{
	static request_authorization_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REQUEST_AUTHORIZATION,
		(xdrproc_t) xdr_request_authorization_props, (caddr_t) &arg1,
		(xdrproc_t) xdr_request_authorization_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

approve_request_token_res *
approve_request_token_1(approve_request_token_props arg1,  CLIENT *clnt)
{
	static approve_request_token_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, APPROVE_REQUEST_TOKEN,
		(xdrproc_t) xdr_approve_request_token_props, (caddr_t) &arg1,
		(xdrproc_t) xdr_approve_request_token_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

request_access_token_res *
request_access_token_1(request_access_token_props arg1,  CLIENT *clnt)
{
	static request_access_token_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REQUEST_ACCESS_TOKEN,
		(xdrproc_t) xdr_request_access_token_props, (caddr_t) &arg1,
		(xdrproc_t) xdr_request_access_token_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

refresh_tokens_res *
refresh_tokens_1(refresh_tokens_props arg1,  CLIENT *clnt)
{
	static refresh_tokens_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REFRESH_TOKENS,
		(xdrproc_t) xdr_refresh_tokens_props, (caddr_t) &arg1,
		(xdrproc_t) xdr_refresh_tokens_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

validate_delegated_action_res *
validate_delegated_action_1(validate_delegated_action_props arg1,  CLIENT *clnt)
{
	static validate_delegated_action_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, VALIDATE_DELEGATED_ACTION,
		(xdrproc_t) xdr_validate_delegated_action_props, (caddr_t) &arg1,
		(xdrproc_t) xdr_validate_delegated_action_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
